apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress
  annotations:
    networking.gke.io/managed-certificates: wordpress-managed-cert
spec:
  ingressClassName: gce
  tls:
  - hosts:
    - wordpress.example.com
    secretName: wordpress-tls
  rules:
  - host: wordpress.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
