{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
  {{- if or .Values.ingress.managedCertificate.enabled .Values.ingress.annotations }}
  annotations:
    {{- if .Values.ingress.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: {{ .Values.ingress.managedCertificate.name | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wordpress.wordpressServiceName" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
